spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bangel_users?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    user: root
    password:
    url: jdbc:mysql://localhost:3306/mysql?useLegacyDatetimeCode=false&serverTimezone=UTC
    #driverClassName: com.mysql.cj.jdbc.Driver
    schemas: bangel_users
    baseline-on-migrate: true

mail-service:
  ribbon:
    ReadTimeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

queue:
  name: messagequeue
fanout:
  exchange: messagequeue-exchange
